### ISSUE TITLE
[Ubuntu 20.04] Version 1.1.4 does not load Python lib and it hangs during launch

### ISSUE THREAD

**Issue by wico-mellone** [tilak-io/tiplot#55]
I downloaded the AppImage v1.1.4 and tried to run it on Ubuntu 20.04, but I am getting the following error:

```shell
gmellone@gmellone-TP ~/Downloads> ./tiplot-1.1.4.AppImage 
Found available port: 5000
[48291] Error loading Python lib '/tmp/.mount_tiplotCvnaJX/resources/api/server/libpython3.10.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /tmp/.mount_tiplotCvnaJX/resources/api/server/libpython3.10.so.1.0)
```
The GUI hangs here:
![image](https://user-images.githubusercontent.com/107674270/225616881-6714bf9e-54cb-49f6-9bd1-405c8a8bef73.png)

---
The v1.1.3 runs with no issues on my machine.

**Comment by HmZyy** [comment]
Hi @wico-mellone,

We've updated the build environment and recompiled the app against Ubuntu 20.04, so you should now be able to use the latest version without any problems.

[Release v1.1.5](https://github.com/tilak-io/tiplot/releases/tag/v1.1.5)

**Comment by wico-mellone** [comment]
Thanks @HmZyy!
