### ISSUE TITLE
Param view Improvements

### ISSUE THREAD

**Issue by tilaktilak** [tilak-io/tiplot#61]
The scroll bar is hidden in 
![image](https://user-images.githubusercontent.com/6662416/236465148-1b2d31d0-a5ad-4c95-a9f5-2bd5419ae607.png)

And would be good to have a search option to easily browse through the params

**Comment by HmZyy** [comment]
![tiplot param search](https://github.com/tilak-io/tiplot/assets/52117777/714146f1-9ee2-4656-bfe5-404485caa15c)

This should do it!
