### ISSUE TITLE
Log Mavic Air3

### ISSUE THREAD

**Issue by benvsn238** [tilak-io/tiplot#99]
Hi,
I have tried Tiplot v1.2.5 on Windows 11 to decod a flightrecord .txt file from a DJI mavic air 3 but Tiplot is loading the file without decoding it.

Could you help me?
Thanks,
Ben

**Comment by HmZyy** [comment]
Hi @benvsn238,

At the moment TiPlot only supports parsing DJI's DAT files, so that's why your TXT file isn't being decoded. Support for TXT files is something we're considering for future updates, but it's not available yet.
